databases:
  - name: ruby4-rails8-flowbite-render-db
    plan: free

services:
  - name: ruby4-rails8-flowbite-render-app
    plan: free
    type: web
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    # preDeployCommand: "bundle exec rails db:migrate" # preDeployCommand only available on paid instance types
    startCommand: "bundle exec rails server"
    healthCheckPath: /up
    autoDeploy: false
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ruby4-rails8-flowbite-render-db
          property: connectionString
      # Render may add a suffix to the database name
      # Ref: https://render.com/docs/blueprint-spec#example-blueprint-file
      - key: DATABASE_NAME
        fromDatabase:
          name: ruby4-rails8-flowbite-render-db
          property: database
      - key: RAILS_ENV
        value: production
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2 # sensible default
